Pandas part 2

In [63]:
import pandas as pd

data = {
    'Name': ['Shivraj', 'Vaibhav', 'Vishal'],
    'Marks': [80, 90, 75]
}

df = pd.DataFrame(data)

# Insert new column using insert() function
df.insert(1, 'Age', [18, 19, 20])
df.insert(2,'Roll_no',[1008,1007,1004])

In [64]:
df

      Name  Age  Roll_no  Marks
0  Shivraj   18     1008     80
1  Vaibhav   19     1007     90
2   Vishal   20     1004     75

* updating Values

In [65]:
df.loc[0,'Marks'] = 99+1
df.loc[1,'Marks'] = 99+1

In [66]:
df

      Name  Age  Roll_no  Marks
0  Shivraj   18     1008    100
1  Vaibhav   19     1007    100
2   Vishal   20     1004     75

* Update Values Using Condition

In [67]:
# df["Marks"] = df["Marks"] 
df.loc[df["Marks"] > 80, "Marks"] = df["Marks"] + 5

In [68]:
df

      Name  Age  Roll_no  Marks
0  Shivraj   18     1008    105
1  Vaibhav   19     1007    105
2   Vishal   20     1004     75

* Removing Column

In [69]:
df.drop(columns = ["Age"],inplace=True)

In [70]:
df.drop("Name",axis=1)

   Roll_no  Marks
0     1008    105
1     1007    105
2     1004     75

# Handling Missing Data

In [71]:
import pandas as pd

data = {
    'Name': ['Shivraj', 'Vaibhav', None],
    'Marks': [80, 90, None]
}

df = pd.DataFrame(data)

* Detect missing / NaN values using isnull()

In [72]:
df.isnull().sum()

Name     1
Marks    1
dtype: int64

In [73]:
df

      Name  Marks
0  Shivraj   80.0
1  Vaibhav   90.0
2      NaN    NaN

* Fill missing values using fillna()

In [74]:
df['Marks'] = df['Marks'].fillna(0)
df['Name'] = df['Name'].fillna("xyz")

In [75]:
df

      Name  Marks
0  Shivraj   80.0
1  Vaibhav   90.0
2      xyz    0.0

* Remove the Row where the value is missing

In [76]:
df.dropna(axis = 0 , inplace=True)

In [77]:
df

      Name  Marks
0  Shivraj   80.0
1  Vaibhav   90.0
2      xyz    0.0

In [78]:
df.isnull()

    Name  Marks
0  False  False
1  False  False
2  False  False

* Fill Missing Values With mean

In [82]:
import pandas as pd

data = {
    'Name' : ['Vaibhav','Shivraj','Vishal','Ram'],
    'Marks': [80, None, 75, 90]
}

df = pd.DataFrame(data)

mean_value = df['Marks'].mean()

df['Marks'] = df['Marks'].fillna(mean_value)

print(df)

      Name      Marks
0  Vaibhav  80.000000
1  Shivraj  81.666667
2   Vishal  75.000000
3      Ram  90.000000