Pandas part 2

In [1]:
import pandas as pd

data = {
    'Name': ['Shivraj', 'Vaibhav', 'Vishal'],
    'Marks': [80, 90, 75]
}

df = pd.DataFrame(data)

# Insert new column using insert() function
df.insert(1, 'Age', [18, 19, 20])
df.insert(2,'Roll_no',[1008,1007,1004])

In [2]:
df

      Name  Age  Roll_no  Marks
0  Shivraj   18     1008     80
1  Vaibhav   19     1007     90
2   Vishal   20     1004     75

* updating Values

In [3]:
df.loc[0,'Marks'] = 99+1
df.loc[1,'Marks'] = 99+1

In [4]:
df

      Name  Age  Roll_no  Marks
0  Shivraj   18     1008    100
1  Vaibhav   19     1007    100
2   Vishal   20     1004     75

* Update Values Using Condition

In [5]:
# df["Marks"] = df["Marks"] 
df.loc[df["Marks"] > 80, "Marks"] = df["Marks"] + 5

In [6]:
df

      Name  Age  Roll_no  Marks
0  Shivraj   18     1008    105
1  Vaibhav   19     1007    105
2   Vishal   20     1004     75

* Removing Column

In [7]:
df.drop(columns = ["Age"],inplace=True)

In [8]:
df.drop("Name",axis=1)

   Roll_no  Marks
0     1008    105
1     1007    105
2     1004     75

# Handling Missing Data

In [9]:
import pandas as pd

data = {
    'Name': ['Shivraj', 'Vaibhav', None],
    'Marks': [80, 90, None]
}

df = pd.DataFrame(data)

* Detect missing / NaN values using isnull()

In [10]:
df.isnull().sum()

Name     1
Marks    1
dtype: int64

In [11]:
df

      Name  Marks
0  Shivraj   80.0
1  Vaibhav   90.0
2      NaN    NaN

* Fill missing values using fillna()

In [12]:
df['Marks'] = df['Marks'].fillna(0)
df['Name'] = df['Name'].fillna("xyz")

In [13]:
df

      Name  Marks
0  Shivraj   80.0
1  Vaibhav   90.0
2      xyz    0.0

* Remove the Row where the value is missing

In [14]:
df.dropna(axis = 0 , inplace=True)

In [15]:
df

      Name  Marks
0  Shivraj   80.0
1  Vaibhav   90.0
2      xyz    0.0

In [16]:
df.isnull()

    Name  Marks
0  False  False
1  False  False
2  False  False

* Fill Missing Values With mean

In [17]:
import pandas as pd

data = {
    'Name' : ['Vaibhav','Shivraj','Vishal','Ram'],
    'Marks': [80, None, 75, 90]
}

df = pd.DataFrame(data)

print(df)
print("After the change")
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

      Name  Marks
0  Vaibhav   80.0
1  Shivraj    NaN
2   Vishal   75.0
3      Ram   90.0
After the change
      Name      Marks
0  Vaibhav  80.000000
1  Shivraj  81.666667
2   Vishal  75.000000
3      Ram  90.000000

In [29]:
import pandas as pd 
data = {
    "Name" : ["Vishal","Shivraj","Vaibhav","Nagesh"],
    "Age" : [20,None,None,15]
}

df = pd.DataFrame(data)
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [30]:
df

      Name   Age
0   Vishal  20.0
1  Shivraj  17.5
2  Vaibhav  17.5
3   Nagesh  15.0

* Interpolation

In [19]:
import pandas as pd

data = {
    'Name' : ['Vaibhav','Shivraj','Vishal','Ram'],
    'Marks': [80, None, 75, 90]
}

df = pd.DataFrame(data)
df['Marks']=df['Marks'].interpolate(method="linear",axis=0)

In [20]:
df

      Name  Marks
0  Vaibhav   80.0
1  Shivraj   77.5
2   Vishal   75.0
3      Ram   90.0

* Methods in interpolation 
linear , polinomial , time

In [21]:
import pandas as pd

data = {
    'Marks': [80, None, 90, 100]
}

df = pd.DataFrame(data)

df = df.interpolate(method='linear')

print(df)

   Marks
0   80.0
1   85.0
2   90.0
3  100.0

In [35]:
import pandas as pd 
data = {
    "Time" : [1,2,3,4,5],
    "Value" : [10,None,30 ,None,50]
}
df = pd.DataFrame(data)
print("Before interpolation")
print(df)

df["Value"] = df["Value"].interpolate(method="linear")
print("After interpolation")
df

Before interpolation
   Time  Value
0     1   10.0
1     2    NaN
2     3   30.0
3     4    NaN
4     5   50.0
After interpolation

   Time  Value
0     1   10.0
1     2   20.0
2     3   30.0
3     4   40.0
4     5   50.0

* When the interpolation used 
* 1 - Timer series data 
2 - numerical data with trends 
3 - Avoid dropping Rows

# Sorting and aggregation

*Sorting data in one column
syntax :- df.sort_values(by="Column_name", True/False)

In [54]:
import pandas as pd 
data = {
    "Name" :['Arun','Varun','Karun'],
    "Age" :[25,36,45],
    "salary":[25000,30000,4000]
}

df = pd.DataFrame(data)
#Sorted Age by the desceding order 
df.sort_values(by="Age",ascending=True,inplace=True)

In [55]:
df

    Name  Age  salary
0   Arun   25   25000
1  Varun   36   30000
2  Karun   45    4000

In [56]:
# Sorted Age by asceding order 
df.sort_values(by="Age",ascending=False,inplace=True)

In [57]:
df

    Name  Age  salary
2  Karun   45    4000
1  Varun   36   30000
0   Arun   25   25000

* Sorting Values From Multiple Columns

* For multiple column sorting in Pandas We need to pass the ascending = [] , We Need to Pass True and False In List

In [64]:
df.sort_values(by=["Age","salary"], ascending=[True,True],inplace=True)

In [65]:
df

    Name  Age  salary
0   Arun   25   25000
1  Varun   36   30000
2  Karun   45    4000

# Aggregation in Pandas

* In pandas, aggregation means combining multiple values into a single summary value. It is commonly used when analyzing data to compute statistics like:

sum
mean (average)
count
min/max
median
standard deviation

Aggregation is often used with groupby().

In [ ]:
df["Age"].sum()

np.float64(100.33333333333334)

In [72]:
df["Age"].mean()

np.float64(35.333333333333336)

In [73]:
df["Age"].min()

np.int64(25)

In [74]:
df["Age"].max()

np.int64(45)

In [75]:
df["Age"].std()

np.float64(10.016652800877813)

In [76]:
df["Age"].var()

np.float64(100.33333333333334)

In [91]:
import pandas as pd 
data = {
    "Department" : ["HR","IT","DEVLOPER",'IT'],
    "Gender" :["M","F","M","M"],
    "Salary" : [100000,4000,45000,8000]
}
df = pd.DataFrame(data)

In [92]:
df

  Department Gender  Salary
0         HR      M  100000
1         IT      F    4000
2   DEVLOPER      M   45000
3         IT      M    8000

# Grouping in Pandas

Grouping in pandas means dividing data into groups based on one or more columns so that you can perform calculations (sum, mean, count, etc.) on each group separately.

Pandas uses the groupby() function for grouping data.

In [93]:
df.groupby('Department')['Salary'].sum()

Department
DEVLOPER     45000
HR          100000
IT           12000
Name: Salary, dtype: int64

In [95]:
df

  Department Gender  Salary
0         HR      M  100000
1         IT      F    4000
2   DEVLOPER      M   45000
3         IT      M    8000

In [96]:
df.groupby(['Department','Gender'])['Salary'].sum()

Department  Gender
DEVLOPER    M          45000
HR          M         100000
IT          F           4000
            M           8000
Name: Salary, dtype: int64