In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("italy-covid-daywise.csv")

In [4]:
df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [5]:
data = {
    "name" : ['ram','shyam','vishal'],
    "Age" : [20,14,21],
    "city" : ['Pune','Nashik','chatrapati sambhajinagar']
}

df = pd.DataFrame(data)

df.to_csv("Student.csv",index=False)
df.to_excel("Student.xlsx",index=False)
df.to_json("Student.json",index=False)

In [6]:
df

     name  Age                      city
0     ram   20                      Pune
1   shyam   14                    Nashik
2  vishal   21  chatrapati sambhajinagar

In [7]:
df = pd.read_csv("italy-covid-daywise.csv")

In [8]:
print("Display First 5 rows ")
df.head()

Display First 5 rows

         date  new_cases  new_deaths  new_tests
0  2019-12-31        0.0         0.0        NaN
1  2020-01-01        0.0         0.0        NaN
2  2020-01-02        0.0         0.0        NaN
3  2020-01-03        0.0         0.0        NaN
4  2020-01-04        0.0         0.0        NaN

In [9]:
print("Display last 5 rows")
df.tail()

Display last 5 rows

           date  new_cases  new_deaths  new_tests
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    str
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: float64(3), str(1)
memory usage: 7.9 KB

* df.describe() is a Pandas function used to generate statistical summary of numerical columns in a DataFrame.

In [11]:
df.describe()

         new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

* df.shape is a Pandas attribute used to find the number of rows and columns in a DataFrame.

In [12]:
df.shape

(248, 4)

* df.columns is a Pandas attribute used to get the column names of a DataFrame.

In [13]:
df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='str')

 * Seleteing the columns from dataframe

Seleting single column

In [14]:
df['new_deaths']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
243    1.0
244    4.0
245    6.0
246    8.0
247    6.0
Name: new_deaths, Length: 248, dtype: float64

Seleting multiple column

In [15]:
subset = df[['date','new_cases']]

In [16]:
subset

           date  new_cases
0    2019-12-31        0.0
1    2020-01-01        0.0
2    2020-01-02        0.0
3    2020-01-03        0.0
4    2020-01-04        0.0
..          ...        ...
243  2020-08-30     1444.0
244  2020-08-31     1365.0
245  2020-09-01      996.0
246  2020-09-02      975.0
247  2020-09-03     1326.0

[248 rows x 2 columns]

# Filtering rows

* Single condition

In [17]:
high_cases = df[df['new_cases'] > 6000]

In [18]:
high_cases

          date  new_cases  new_deaths  new_tests
82  2020-03-22     6557.0       795.0        NaN
87  2020-03-27     6153.0       660.0        NaN

* Multiple Condition

use & Condition

In [19]:
high_case = df[(df['new_cases'] > 5000) & (df['new_deaths'] > 650)]

In [20]:
high_case

          date  new_cases  new_deaths  new_tests
82  2020-03-22     6557.0       795.0        NaN
85  2020-03-25     5249.0       743.0        NaN
86  2020-03-26     5210.0       685.0        NaN
87  2020-03-27     6153.0       660.0        NaN
88  2020-03-28     5959.0       971.0        NaN
89  2020-03-29     5974.0       887.0        NaN
90  2020-03-30     5217.0       758.0        NaN

used OR condition

In [21]:
high = df[(df['new_cases'] > 5000) | (df['new_deaths'] > 650)]

In [22]:
high

          date  new_cases  new_deaths  new_tests
80  2020-03-20     5322.0       429.0        NaN
81  2020-03-21     5986.0       625.0        NaN
82  2020-03-22     6557.0       795.0        NaN
83  2020-03-23     5560.0       649.0        NaN
85  2020-03-25     5249.0       743.0        NaN
86  2020-03-26     5210.0       685.0        NaN
87  2020-03-27     6153.0       660.0        NaN
88  2020-03-28     5959.0       971.0        NaN
89  2020-03-29     5974.0       887.0        NaN
90  2020-03-30     5217.0       758.0        NaN
91  2020-03-31     4050.0       810.0        NaN
92  2020-04-01     4053.0       839.0        NaN
93  2020-04-02     4782.0       727.0        NaN
94  2020-04-03     4668.0       760.0        NaN
95  2020-04-04     4585.0       764.0        NaN
96  2020-04-05     4805.0       681.0        NaN

Part 2

In [23]:
df['new_column'] = df['new_cases'] * 0.1

In [24]:
df

           date  new_cases  new_deaths  new_tests  new_column
0    2019-12-31        0.0         0.0        NaN         0.0
1    2020-01-01        0.0         0.0        NaN         0.0
2    2020-01-02        0.0         0.0        NaN         0.0
3    2020-01-03        0.0         0.0        NaN         0.0
4    2020-01-04        0.0         0.0        NaN         0.0
..          ...        ...         ...        ...         ...
243  2020-08-30     1444.0         1.0    53541.0       144.4
244  2020-08-31     1365.0         4.0    42583.0       136.5
245  2020-09-01      996.0         6.0    54395.0        99.6
246  2020-09-02      975.0         8.0        NaN        97.5
247  2020-09-03     1326.0         6.0        NaN       132.6

[248 rows x 5 columns]

Adding Column using insert()